use_frameworks!

platform :ios, '9.0'

target 'YYImageWebp_Example' do
  pod 'YYImageWebp', :path => '../'

  target 'YYImageWebp_Tests' do
    inherit! :search_paths

    
  end
  
  
#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          target.build_configurations.each do |config|
#              config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#          end
#      end
#  end
   
  
end
